version: '3'
services:
  jenkins:
    image: jenkins/jenkins:2.440.1-lts-jdk21
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always
volumes:
  jenkins_home: