version: '3'
services:
  jenkins:
    image: jenkins/jenkins:2.440.1-lts-jdk21
    ports:
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always
volumes:
  jenkins_home: